### ISSUE TITLE
Error while trying to compile on Debian buster

### ISSUE THREAD

**Issue by Nennala** [Makeblock-official/mBlock#79]
Hi, I've tried the method to compile the mblock soft because the .deb package have to many problems on Linux and it's a i386 library.

After installing npm and did the `npm install` i did `npm run rebuild-serialport`, `npm run rebuild-hid`, etc, but all the time I get that time of error with exactly the same token error : 

`> mBlock@4.0.0 rebuild-hid /home/daphne/Documents/Applications/mBlock
> electron-rebuild -f -w node-hid

/home/daphne/Documents/Applications/mBlock/node_modules/electron-rebuild/lib/src/rebuild.js:73
                depKeys.push(...Object.keys(rootPackageJson.dependencies || {}));
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/daphne/Documents/Applications/mBlock/node_modules/electron-rebuild/lib/src/cli.js:17:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! mBlock@4.0.0 rebuild-hid: `electron-rebuild -f -w node-hid`
npm ERR! Exit status 1`

Did I make something wrong ? What I have to do if I want to fix that issue and finally have a functional mblock on Linux ?

**Comment by nzbart** [comment]
@Nennala I just managed to get the `master` branch building on the latest version of Debian Testing. I needed to install the following Debian packages:

* libbluetooth-dev
* libusb-1.0-0-dev

Installing these packages and then following the [installation steps in the Readme](https://github.com/Makeblock-official/mBlock/blob/master/ReadMe.md#user-content-build-guide) should work.
