### ISSUE TITLE
Unable to start mBlock 4.0.0 on Ubuntu MATE 20.04.3 LTS because of "Harfbuzz version too old (1.2.7)" error

### ISSUE THREAD

**Issue by N0rbert** [Makeblock-official/mBlock#93]
I have downloaded the mBlock 4.0.0 to my Ubuntu MATE 20.04.3 LTS using commands below:

```
sudo apt-get update
sudo apt-get install libgconf-2-4

cd ~/Downloads
wget -c https://github.com/Makeblock-official/mBlock/releases/download/V4.0.0-Linux/mBlock-4.0.0-linux-4.0.0.tar.gz
tar -xf mBlock-4.0.0-linux-4.0.0.tar.gz
```

On launch it shows the following message:

```
cd ~/Downloads/mBlock
./mblock

$ ./mblock
/home/mate/Downloads/mBlock/resources/tools/arduino
app listening on port 7070!

(mblock:7529): Pango-ERROR **: 22:27:16.382: Harfbuzz version too old (1.2.7)


```

**Comment by N0rbert** [comment]
The same happens with deb-package as follows:

```
cd ~/Downloads
wget -c http://mblockapp.oss-cn-hongkong.aliyuncs.com/mBlock4.0/mBlock_4.0.4_amd64.deb
sudo apt install ./mBlock_4.0.4_amd64.deb
```

I got the following errors:

```
$ /opt/makeblock/mBlock/mblock 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::7070
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/opt/makeblock/mBlock/resources/app.asar/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/opt/makeblock/mBlock/resources/app.asar/main.js:39:6)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

(mblock:8864): Pango-ERROR **: 22:55:45.176: Harfbuzz version too old (1.2.7)

Trace/breakpoint trap
```

**Comment by ghost** [comment]
I cannot install mblock locally on ubuntu 20.04 

``#!/bin/bash  
wget -O mblock.tar.gz https://github.com/Makeblock-official/mBlock/releases/download/V4.0.0-Linux/mBlock-4.0.0-linux-4.0.0.tar.gz  
tar zxvf mblock.tar.gz    
rm mblock.tar.gz    
mv mBlock $HOME    
cd $HOME    
cd mBlock      
./mblock``

With the above script the following error appears:

![mblock_problems04](https://user-images.githubusercontent.com/78594804/154963417-4859a974-a664-4519-afdc-3d4cc286fcfb.png)

![mblock_problems03](https://user-images.githubusercontent.com/78594804/154963576-2c55a455-b165-4160-8d9e-5d51ad6191fa.png)

**kern  :warn  : [feb21 14:15] process 'opt/makeblock/mBlock/mblock' started with executable stack  
kern  :info  : [  +0,666983] traps: mblock[15875] trap int3 ip:7f2e4b680295 sp:7ffe676a18e0 error:0 in libglib-2.0.so.0.6400.6[7f2e4b644000+84000]  
kern  :info  : [feb21 14:17] traps: mblock[16232] trap int3 ip:7f2fdf5ea295 sp:7ffd43a4ea10 error:0 in libglib-2.0.so.0.6400.6[7f2fdf5ae000+84000]  
kern  :info  : [ +33,023534] perf: interrupt took too long (2549 > 2500), lowering kernel.perf_event_max_sample_rate to 78250  
kern  :info  : [feb21 14:29] traps: mblock[18485] trap int3 ip:7f3a82771295 sp:7fff7e381570 error:0 in libglib-2.0.so.0.6400.6[7f3a82735000+84000]  **

I have tried with the next script to: (debian package)
``
#!/bin/bash  
wget -O mblock.deb http://mblockapp.oss-cn-hongkong.aliyuncs.com/mBlock4.0/mBlock_4.0.4_amd64.deb  
sudo dpkg -i mblock.deb``  

With the above script the following error appears:

**Gtk-Message: 14:29:24.320: Failed to load module "canberra-gtk-module"  
/home/grafeno30/mBlock/resources/tools/arduino  
app listening on port 7070!

(mblock:18424): Pango-ERROR : 14:29:24.741: Harfbuzz version too old (1.2.7)**

My version of operating system is:

**NAME="Ubuntu"  
VERSION="20.04.3 LTS (Focal Fossa)"  
ID=ubuntu  
ID_LIKE=debian  
PRETTY_NAME="Ubuntu 20.04.3 LTS"  
VERSION_ID="20.04"  
HOME_URL="https://www.ubuntu.com/"  
SUPPORT_URL="https://help.ubuntu.com/"  
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"  
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"  
VERSION_CODENAME=focal  
UBUNTU_CODENAME=focal**

Thanks in advance

**Comment by jondo** [comment]
See also https://askubuntu.com/questions/1393396/cant-install-mblock-error-pango, https://forum.makeblock.com/t/i-cannot-install-mblock-locally-on-ubuntu-20-04-cannot-use-mbot/19767, and https://forum.makeblock.com/t/mblock-26755-pango-error-1025-473-harfbuzz-version-too-old-1-2-7/19728 (unfortunately currently without more info).

**Comment by jiapei100** [comment]
It looks they are **NOT** maintaining this any more. 

- the chip on **CyberPi** is an **ESP32**
- the software **mBlock** is based on **Scratch**
- what's more, **mBlock** is in JS but there is **ONLY** download for Windows and Mac (https://mblock.makeblock.com/en-us/download/mlink/) . 
- **mLink2** is **NOT** well supported under Linux as well, at least, the version of [mlink on github](https://github.com/audetto/mblock-mlink) is **ONLY** 1.4, **NOT** 2.0.

I would really like to recommend we DON'T use mBlock under Linux. At least for now.
